services:
    _defaults:
        autowire: true
        autoconfigure: true

    LightSaml\Build\Container\BuildContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\BuildContainer
        public: true

    LightSaml\Build\Container\SystemContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\SystemContainer
        arguments:
            $eventDispatcher: "@lightsaml.system.event_dispatcher"
            $logger: "@lightsaml.system.logger"

    LightSaml\Build\Container\PartyContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\PartyContainer
        arguments:
            $idpEntityDescriptorStore: "@lightsaml.party.idp_entity_descriptor_store"
            $spEntityDescriptorStore: "@lightsaml.party.sp_entity_descriptor_store"

    LightSaml\Build\Container\StoreContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\StoreContainer

    LightSaml\Build\Container\ProviderContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\ProviderContainer

    LightSaml\Build\Container\CredentialContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\CredentialContainer
        arguments:
            - "@lightsaml.credential.credential_store"

    LightSaml\Build\Container\ServiceContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\ServiceContainer
        arguments:
            $signatureResolver: '@LightSaml\Resolver\Signature\OwnSignatureResolver'
            $endpointResolver: '@lightsaml.service.endpoint_resolver'
            $credentialResolver: '@lightsaml.service.credential_resolver'

    LightSaml\Build\Container\OwnContainerInterface:
        class: LightSaml\SymfonyBridgeBundle\Bridge\Container\OwnContainer
        arguments:
            $entityDescriptorProvider: "@lightsaml.own.entity_descriptor_provider"
            $credentialStore: "@lightsaml.own.credential_store"
            $entityId: "%lightsaml.own.entity_id%"
