services:
    _defaults:
        autowire: true
        autoconfigure: true

    lightsaml.party.sp_entity_descriptor_store:
        class: LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore

    lightsaml.party.idp_entity_descriptor_store:
        class: LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore

    lightsaml.party.idp_entity_descriptor_store.file:
        class: LightSaml\Store\EntityDescriptor\FileEntityDescriptorStore
        arguments:
            - ~ # filename
        abstract: true

    LightSaml\Store\TrustOptions\TrustOptionsStoreInterface:
        class: LightSaml\Store\TrustOptions\CompositeTrustOptionsStore
