services:
    _defaults:
        autowire: true
        autoconfigure: true

    LightSaml\Builder\Profile\Metadata\MetadataProfileBuilder: ~

    lightsaml.profile.metadata:
        alias: LightSaml\Builder\Profile\Metadata\MetadataProfileBuilder

    LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpSendAuthnRequestProfileBuilderFactory: ~

    lightsaml.profile.login_factory:
        alias: LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpSendAuthnRequestProfileBuilderFactory

    LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpReceiveResponseProfileBuilder: ~

    lightsaml.profile.acs:
        alias: LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpReceiveResponseProfileBuilder
