services:
    _defaults:
        autowire: true
        autoconfigure: true

    LightSaml\Provider\Attribute\AttributeValueProviderInterface:
        class: LightSaml\Provider\Attribute\FixedAttributeValueProvider

    LightSaml\Provider\Session\SessionInfoProviderInterface:
        class: LightSaml\Provider\Session\FixedSessionInfoProvider

    LightSaml\Provider\NameID\NameIdProviderInterface:
        class: LightSaml\Provider\NameID\FixedNameIdProvider
