services:
    _defaults:
        autowire: true
        autoconfigure: true

    LightSaml\Validator\Model\NameId\NameIdValidatorInterface:
        class: LightSaml\Validator\Model\NameId\NameIdValidator

    LightSaml\Validator\Model\Statement\StatementValidatorInterface:
        class: LightSaml\Validator\Model\Statement\StatementValidator

    LightSaml\Validator\Model\Subject\SubjectValidatorInterface:
        class: LightSaml\Validator\Model\Subject\SubjectValidator

    LightSaml\Validator\Model\Assertion\AssertionTimeValidatorInterface:
        class: LightSaml\Validator\Model\Assertion\AssertionTimeValidator

    LightSaml\Validator\Model\Assertion\AssertionValidatorInterface:
        class: LightSaml\Validator\Model\Assertion\AssertionValidator

    lightsaml.service.endpoint_resolver.binding:
        class: LightSaml\Resolver\Endpoint\BindingEndpointResolver

    lightsaml.service.endpoint_resolver.descriptor_type:
        class: LightSaml\Resolver\Endpoint\DescriptorTypeEndpointResolver

    LightSaml\Resolver\Endpoint\ServiceTypeEndpointResolver: ~

    lightsaml.service.endpoint_resolver.service_type:
        alias: LightSaml\Resolver\Endpoint\ServiceTypeEndpointResolver

    LightSaml\Resolver\Endpoint\IndexEndpointResolver: ~

    lightsaml.service.endpoint_resolver.index:
        alias: LightSaml\Resolver\Endpoint\IndexEndpointResolver

    LightSaml\Resolver\Endpoint\LocationEndpointResolver: ~

    lightsaml.service.endpoint_resolver.location:
        alias: LightSaml\Resolver\Endpoint\LocationEndpointResolver

    lightsaml.service.endpoint_resolver:
        alias: LightSaml\Resolver\Endpoint\CompositeEndpointResolver

    LightSaml\Resolver\Endpoint\CompositeEndpointResolver:
        calls:
            - [ add, [ "@lightsaml.service.endpoint_resolver.binding" ] ]
            - [ add, [ "@lightsaml.service.endpoint_resolver.descriptor_type" ] ]
            - [ add, [ "@lightsaml.service.endpoint_resolver.service_type" ] ]
            - [ add, [ "@lightsaml.service.endpoint_resolver.index" ] ]
            - [ add, [ "@lightsaml.service.endpoint_resolver.location" ] ]

    LightSaml\Binding\BindingFactoryInterface:
        class: LightSaml\Binding\BindingFactory
        arguments:
            $eventDispatcher: "@lightsaml.system.event_dispatcher"

    LightSaml\Resolver\Credential\Factory\CredentialResolverFactory:
        arguments:
            $credentialStore: "@lightsaml.credential.credential_store"

    lightsaml.service.credential_resolver_factory:
        alias: LightSaml\Resolver\Credential\Factory\CredentialResolverFactory

    lightsaml.service.credential_resolver:
        class: LightSaml\Resolver\Credential\CompositeFilterResolver
        # factory: ["@lightsaml.service.credential_resolver_factory", build] # set in extension, differently based on symfony version

    LightSaml\Resolver\Signature\OwnSignatureResolver:
        arguments:
            $credentialResolver: "@lightsaml.service.credential_resolver"

    lightsaml.service.signature_resolver:
        alias: LightSaml\Resolver\Signature\OwnSignatureResolver

    LightSaml\Validator\Model\Signature\SignatureValidatorInterface:
        class: LightSaml\Validator\Model\Signature\SignatureValidator
        arguments:
            $credentialResolver: "@lightsaml.service.credential_resolver"

    LightSaml\Resolver\Session\SessionProcessorInterface:
        class: LightSaml\Resolver\Session\SessionProcessor

