services:
  _defaults:
    autowire: true
    autoconfigure: true

  LightSaml\Store\Request\RequestStateStoreInterface:
    class: LightSaml\SymfonyBridgeBundle\Store\Request\Symfony53RequestStateSessionStore
    arguments:
      $providerId: "%lightsaml.store.request_session_prefix%"
      $prefix: "%lightsaml.store.request_session_suffix%"

  LightSaml\Store\Sso\SsoStateStoreInterface:
    class: LightSaml\SymfonyBridgeBundle\Store\Sso\Symfony53SsoStateSessionStore
    arguments:
      $key: "%lightsaml.store.sso_state_session_key%"
    public: true
