services:
    _defaults:
        autowire: true
        autoconfigure: true

    LightSaml\Provider\TimeProvider\TimeProviderInterface:
        class: LightSaml\Provider\TimeProvider\SystemTimeProvider

    lightsaml.system.event_dispatcher: '@event_dispatcher'
    lightsaml.system.logger: '@logger'
